// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOeM_Qk-RkWeosUgGgW49kzaA39MN0tj8',
    appId: '1:402468133523:web:ae52870abc2d24073ecb66',
    messagingSenderId: '402468133523',
    projectId: 'chat-app-6a523',
    authDomain: 'chat-app-6a523.firebaseapp.com',
    storageBucket: 'chat-app-6a523.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHua3rKMx4-v8VGP595h4JnA56oSGuQ2c',
    appId: '1:402468133523:android:3c0e188870142b453ecb66',
    messagingSenderId: '402468133523',
    projectId: 'chat-app-6a523',
    storageBucket: 'chat-app-6a523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpwElflWYYRKtk_JWoeuaKT9av2tTcLT0',
    appId: '1:402468133523:ios:81172e8153e606dc3ecb66',
    messagingSenderId: '402468133523',
    projectId: 'chat-app-6a523',
    storageBucket: 'chat-app-6a523.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpwElflWYYRKtk_JWoeuaKT9av2tTcLT0',
    appId: '1:402468133523:ios:81172e8153e606dc3ecb66',
    messagingSenderId: '402468133523',
    projectId: 'chat-app-6a523',
    storageBucket: 'chat-app-6a523.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOeM_Qk-RkWeosUgGgW49kzaA39MN0tj8',
    appId: '1:402468133523:web:0660c2d57594f0a33ecb66',
    messagingSenderId: '402468133523',
    projectId: 'chat-app-6a523',
    authDomain: 'chat-app-6a523.firebaseapp.com',
    storageBucket: 'chat-app-6a523.firebasestorage.app',
  );
}
